// import { ICollectionModel } from "@drk/src/Model/ICollectionModel";
// import { IEntityModel } from "@drk/src/Model/IEntityModel";
// import { IPropertyModel } from "@drk/src/Model/IPropertyModel";

// export const entity: IEntityModel = {
// 	collectionDependents: [],
// 	collectionDictionary: {},
// 	collections: [],
// 	componentFactories: [],
// 	dependents: [],
// 	displayName: 'ModelDisplayName',
// 	displayTypeName: 'ModelDisplayTypeName',
// 	interfaces: [],
// 	members: [],
// 	modelType: 'EntityModel',
// 	name: 'ModelName',
// 	namespace: ['Darkengines', 'Model'],
// 	operators: [],
// 	parent: null,
// 	primaryKey: [],
// 	properties: [],
// 	propertyDictionary: {},
// 	referenceDictionary: {},
// 	references: [],
// 	summaryCollections: [],
// 	summaryProperties: [],
// 	summaryReferences: [],
// };

// const name: IPropertyModel = {
// 	componentFactories: [],
// 	displayName: 'Name',
// 	displayTypeName: 'String',
// 	format: null,
// 	isAutoGenerated: false,
// 	isNullable: false,
// 	maxLength: 256,
// 	modelType: 'PropertyModel',
// 	name: 'name',
// 	operators: [],
// 	typeName: 'String',
// };

// const typeName: IPropertyModel = {
// 	componentFactories: [],
// 	displayName: 'Type name',
// 	displayTypeName: 'String',
// 	format: null,
// 	isAutoGenerated: false,
// 	isNullable: false,
// 	maxLength: 256,
// 	modelType: 'PropertyModel',
// 	name: 'typeName',
// 	operators: [],
// 	typeName: 'String',
// };
// const displayName: IPropertyModel = {
// 	componentFactories: [],
// 	displayName: 'Display name',
// 	displayTypeName: 'String',
// 	format: null,
// 	isAutoGenerated: false,
// 	isNullable: false,
// 	maxLength: 256,
// 	modelType: 'PropertyModel',
// 	name: 'displayName',
// 	operators: [],
// 	typeName: 'String',
// };
// const displayTypeName: IPropertyModel = {
// 	componentFactories: [],
// 	displayName: 'Display type name',
// 	displayTypeName: 'String',
// 	format: null,
// 	isAutoGenerated: false,
// 	isNullable: false,
// 	maxLength: 256,
// 	modelType: 'PropertyModel',
// 	name: 'displayTypeName',
// 	operators: [],
// 	typeName: 'String',
// };

// const entityProperties = [
//     name,
//     typeName,
//     displayName,
//     displayTypeName
// ];

// const properties: ICollectionModel = {
//     name: 'Properties',
//     displayName: 'Properties',
//     displayTypeName: 'Property',
//     typeName: 'Property',
// 	type: null,
// 	foreignKey: [],
// 	targetForeignKey: [],
// 	isDependentToPrincipal: false,
// 	modelType: 'CollectionModel',
// };

// const references: ICollectionModel = {
// 	name: 'References',
//     displayName: 'References',
//     displayTypeName: 'Reference',
//     typeName: 'Reference',
// 	type: null,
// 	foreignKey: [],
// 	targetForeignKey: [],
// 	isDependentToPrincipal: false,
// 	modelType: 'CollectionModel',
// };

// const collections: ICollectionModel = {
// 	name: 'Collections',
//     displayName: 'Collections',
//     displayTypeName: 'Collection',
//     typeName: 'Collection'
// 	type: null,
// 	foreignKey: [],
// 	targetForeignKey: [],
// 	isDependentToPrincipal: false,
// 	modelType: 'CollectionModel',
// };

// const entityCollections = [
//     properties,
//     references,
//     collections
// ]