import { IEntityModel } from "@drk/src/Model/IEntityModel";
import { IPropertyModel } from "@drk/src/Model/IPropertyModel";
import { IReferenceModel } from "@drk/src/Model/IReferenceModel";

const propertyModelName: IPropertyModel = {
    componentFactories: [],
	displayName: 'Model name',
	displayTypeName: 'String',
	format: null,
	isAutoGenerated: false,
	isNullable: false,
	maxLength: 256,
	modelType: 'PropertyModel',
	name: 'ModelName',
	operators: [],
	typeName: 'String'
};

const propertyName: IPropertyModel = {
    componentFactories: [],
	displayName: 'Name',
	displayTypeName: 'String',
	format: null,
	isAutoGenerated: false,
	isNullable: false,
	maxLength: 256,
	modelType: 'PropertyModel',
	name: 'Name',
	operators: [],
	typeName: 'String'
};

const propertyDisplayName: IPropertyModel = {
    componentFactories: [],
	displayName: 'Display name',
	displayTypeName: 'String',
	format: null,
	isAutoGenerated: false,
	isNullable: false,
	maxLength: 256,
	modelType: 'PropertyModel',
	name: 'DisplayName',
	operators: [],
	typeName: 'String'
};

const propertyTypeName: IPropertyModel = {
    componentFactories: [],
	displayName: 'Type name',
	displayTypeName: 'String',
	format: null,
	isAutoGenerated: false,
	isNullable: false,
	maxLength: 256,
	modelType: 'PropertyModel',
	name: 'TypeName',
	operators: [],
	typeName: 'String'
};

const propertyFormat: IPropertyModel = {
    componentFactories: [],
	displayName: 'Format',
	displayTypeName: 'String',
	format: null,
	isAutoGenerated: false,
	isNullable: false,
	maxLength: 256,
	modelType: 'PropertyModel',
	name: 'Format',
	operators: [],
	typeName: 'String'
};

const propertyNullability: IPropertyModel = {
    componentFactories: [],
	displayName: 'Is Nullable',
	displayTypeName: 'Boolean',
	format: null,
	isAutoGenerated: false,
	isNullable: false,
	maxLength: 256,
	modelType: 'PropertyModel',
	name: 'IsNullable',
	operators: [],
	typeName: 'Boolean'
};

const propertyAutoGeneration: IPropertyModel = {
    componentFactories: [],
	displayName: 'Is auto generated',
	displayTypeName: 'Boolean',
	format: null,
	isAutoGenerated: false,
	isNullable: false,
	maxLength: 256,
	modelType: 'PropertyModel',
	name: 'IsAutoGenerated',
	operators: [],
	typeName: 'Boolean'
};

const propertyMaxLength: IPropertyModel = {
    componentFactories: [],
	displayName: 'Maximum length',
	displayTypeName: 'Int32',
	format: null,
	isAutoGenerated: false,
	isNullable: true,
	modelType: 'PropertyModel',
	name: 'MaxLength',
	operators: [],
	typeName: 'Int32',
}

const propertyProperties = [
    propertyModelName,
    propertyName,
    propertyTypeName,
    propertyDisplayName,
    propertyFormat,
    propertyAutoGeneration,
    propertyNullability,
    propertyMaxLength
]

const propertyEntityModel: IEntityModel = {
	collectionDependents: [],
	collectionDictionary: {},
	collections: [],
	componentFactories: [],
	dependents: [],
	displayName: 'Property',
	displayTypeName: 'Property',
	interfaces: [],
	members: [],
	modelType: 'EntityModel',
	name: 'Property',
	namespace: ['Darkengines', 'Model'],
	operators: [],
	parent: null,
	primaryKey: [],
	properties: propertyProperties,
	propertyDictionary: {},
	referenceDictionary: {},
	references: [],
	summaryCollections: [],
	summaryProperties: [],
	summaryReferences: [],
};

// const propertyModelReference: IReferenceModel = {
//     name: 'Model',
//     displayName: 'Model',
//     type: model,
//     foreignKey: [propertyModelName],
//     targetForeignKey: [modelName]
//     isDependentToPrincipal: true,
//     modelType: 'ReferenceModel',
// }