// const referenceEntityModel: IEntityModel = {
// 	collectionDependents: [],
// 	collectionDictionary: {},
// 	collections: [],
// 	componentFactories: [],
// 	dependents: [],
// 	displayName: 'ModelDisplayName',
// 	displayTypeName: 'ModelDisplayTypeName',
// 	interfaces: [],
// 	members: [],
// 	modelType: 'EntityModel',
// 	name: 'ModelName',
// 	namespace: ['Darkengines', 'Model'],
// 	operators: [],
// 	parent: null,
// 	primaryKey: [],
// 	properties: [properties.name],
// 	propertyDictionary: {},
// 	referenceDictionary: {},
// 	references: [],
// 	summaryCollections: [],
// 	summaryProperties: [],
// 	summaryReferences: [],
// };