import { IMember } from './IMember';

export interface IPropertyModel extends IMember {
	isNullable: boolean;
	typeName: string;
	maxLength?: number;
	format: string;
	isAutoGenerated: boolean;
	modelType: 'PropertyModel';
}
